### ISSUE TITLE
Internal Server Error occured

### ISSUE THREAD

**Issue by maaaaaajin** [brahmai-research/aiforcause#12]
Just writing on a little project as i noticed that i get the error-message: openai.InternalServerError: Internal Server Error
So i tried to take only the example code to exclude possible mistakes by me.
`from openai import OpenAI
client = OpenAI(
  api_key="testing",
  base_url="https://aiforcause.deepnight.tech/openai/"
)

response = client.chat.completions.create(
  model="gpt-35-turbo",   # gpt-35-turbo (GPT-3.5 Turbo - 4k) || gpt-35-turbo-16k (GPT-3.5 Turbo 16k) || gpt-4-turbo (GPT-4 Turbo)
  messages=["Hello World! Test123."],
  stream=False # or True
)

print(response.choices[0].message.content)` 
Is there any problem with the endpoint or did i miss something?

**Comment by theone2277** [comment]
message = [{"role": "user", "content": "Hello! Could you solve 2+2?"}]

**Comment by maaaaaajin** [comment]
Yeah that's my bad. Obviously it works now. I think i made the mistake cause i tried to solve another open issue, where the message was exactly what i typed. Thanks for the help
