### ISSUE TITLE
No or empty answer...

### ISSUE THREAD

**Issue by SmEe037** [brahmai-research/aiforcause#7]
Hello! A great job. Thank you very much! ;)

But unfortunately I don't get an answer via PHP.
Could someone please look at my script?

`<?php

$api_key = "OnlyAtest";
$base_url = "https://aiforcause.deepnight.tech/openai/";

$data = array(
    "model" => "gpt-35-turbo", // gpt-35-turbo (GPT-3.5 Turbo - 4k) || gpt-35-turbo-16k (GPT-3.5 Turbo 16k) || gpt-4-turbo (GPT-4 Turbo)
    "messages" => ["Hello World! Test123."],
    "stream" => true // or false
);

$options = array(
    'http' => array(
        'header'  => "Content-type: application/json\r\n",
        'method'  => 'POST',
        'content' => json_encode($data)
    )
);

$context  = stream_context_create($options);
$response = file_get_contents($base_url . 'chat/completions/create?api_key=' . $api_key, false, $context);

$response_data = json_decode($response, true);

if (isset($response_data['choices'][0]['message']['content'])) {
    echo $response_data['choices'][0]['message']['content'];
} else {
echo $response_data;  
echo "Keine Antwort erhalten.";
}

?>
`

THX! ;)

**Comment by brahmai-research** [comment]
Hey @SmEe037,
Thanks for bringing this to our attention.
We'll have a look at it and get back to you ASAP!

Cheers ✌️
Team [BRAHMAI](https://brahmai.in)

**Comment by SmEe037** [comment]
THX! ;)

**Comment by Fedox-die-Ente** [comment]
> Hey @SmEe037, Thanks for bringing this to our attention. We'll have a look at it and get back to you ASAP!
> 
> Cheers ✌️ Team [BRAHMAI](https://brahmai.in)

Hey, I love your project. How long do you think it will take until this problem is fixed? It would be very helpful to me at the moment :)

**Comment by SmEe037** [comment]
Let's see. Unfortunately I can't say that yet. I'm playing myself. ;)

**Comment by Fedox-die-Ente** [comment]
> Let's see. Unfortunately I can't say that yet. I'm playing myself. ;)

Take ur time, im excited :D

**Comment by brahmai-research** [comment]
Greetings, we're still trying to figure out the problem. Since there are no error logs, it's a little hard to debug.

Thanks.

**Comment by Stoppedwumm** [comment]
> Greetings, we're still trying to figure out the problem. Since there are no error logs, it's a little hard to debug.
> 
> Thanks.

no problems, your the giga chads of ai

**Comment by theone2277** [comment]
@brahmai-research hello, but since about 24 hours, the api has not responded anything in any model. are you aware about it too?

**Comment by brahmai-research** [comment]
Hey @theone2277, yes, we are aware of the issue. It does happen at times.
It's the rate-limit error that we're facing.
We have submitted the request to Azure to increase the quota and are waiting for their response right now.

Apologies for this inconvenience. We'll have it all up and running soon.

**Comment by brahmai-research** [comment]
Greetings,
We regret to inform you that our request for the rate limit increase was denied. We don't know why exactly that happened but we're creating an appeal against it.

However, as we see the server logs, there are constant requests being made.
This leads to the conclusion of API spamming.

We'll keep you all posted.


Regards,
Team BRAHMAI

**Comment by feeeedox** [comment]
@brahmai-research Maybe add a limiter so people can't spam the api
