### ISSUE TITLE
spelling mistake in rate limit apology

### ISSUE THREAD

**Issue by Dvd15** [brahmai-research/aiforcause#8]
Just a quick info that you have a spelling mistake in the rate limit error, you wrote Aplologies, just saw it and thought I would let you know while I wait
![image](https://github.com/brahmai-research/aiforcause/assets/57320627/02b3bd6a-c177-45c8-b37c-56f029ffdfcb)
Thank you guys for your service and this project.

**Comment by brahmai-research** [comment]
Thanks for bringing this to our attention. We'll fix it right away.
