### ISSUE TITLE
API doesn't respond

### ISSUE THREAD

**Issue by Stoppedwumm** [brahmai-research/aiforcause#9]
I am trying your api out, but using

```bash
curl https://aiforcause.deepnight.tech/models
```

doesn't work, as the server doesn't respond

**Comment by Stoppedwumm** [comment]
Thanks!

**Comment by brahmai-research** [comment]
Greetings @Stoppedwumm,

The server is back up. You can give it a shot now!

Cheers ✌️
Team BRAHMAI

**Comment by Stoppedwumm** [comment]
Works!
